### ISSUE TITLE
Swap the precedence of README.md and doc/index.md.

### ISSUE THREAD

**Issue by mylo88** [monome-community/norns-community#12] opened 2023-05-18 18:56 UTC
Change the priority order for finding documentation to:  `doc/index.md`, `README.md`. The current code uses the reverse order.

There are two reasons for this change. I'll start with the simple reason: the change aligns the order with cover images where images in `doc/` have priority over images at the root.

The second and more important reason is that the change allows the project author to target different audiences with different documentation. The author writes end-user documentation in `doc/index.md` for display on [community.norns](https://norns.community/). The author writes developer in `README.md` for display on GitHub.

As the code currently stands, `doc/index.md` is not directly shown to a user when `README.md` is present.

This change does not impact existing projects because none of the projects in the [community catalog](https://github.com/monome/norns-community) has a `doc/index.md`.

**Comment by p3r7** [comment] 2023-05-18 19:54
Tyler could confirm but i believe this to be a bug.

thanks for reporting!

**Comment by tyleretters** [comment] 2023-05-18 20:31
not a bug! a good catch. i agree the order should be flipped.

**Comment by tyleretters** [comment] 2023-05-19 15:54
fixed with #13

**Closed by tyleretters** 2023-05-19 15:54 UTC
